### ISSUE TITLE
Command map table is a disaster

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap-7mode-transition#1]
@netapp-forry You wanted to discuss. 

Ref topic: https://review.docs.netapp.com/us-en/ontap-7mode-transition_catalyst-adoc/command-map/reference_7_mode_to_clustered_data_ontap_command_map.html#navigation-table

**Comment by netapp-aherbin** [comment]
This table has been updated as part of the repo clean-up:
https://docs.netapp.com/us-en/ontap-7mode-transition/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html
