### ISSUE TITLE
This is an empty shell of a document

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/ontap-7mode-transition#11]
Page: [Host and Storage Information Collection Guide](https://docs.netapp.com/us-en/ontap-7mode-transition/inventory-collect/index.html)

Please add installation requirements, installation instructions, and usage instructions to this shell placeholder document.

**Comment by netapp-forry** [comment]
Thanks Rob -- this issue is already on our radar -- I'll follow up with you separately.

**Comment by netapp-forry** [comment]
This is a known issue that we will address in the future if prioritization and resources permit.
