### ISSUE TITLE
Missing Step - Create Destination Volume on C-Mode System

### ISSUE THREAD

**Issue by s1m0** [NetAppDocs/ontap-7mode-transition#13]
Page: [Transitioning a stand-alone volume](https://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/task_transitioning_a_stand_alone_volume.html)

there is no information on what options to use when creating the transition destination volume on the C-Mode system.

**Comment by netapp-barbe** [comment]
Hello Simon, thank you for raising this issue. I'll investigate and get back to you.

**Comment by netapp-barbe** [comment]
Fixed https://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/task_transitioning_a_stand_alone_volume.html
