### ISSUE TITLE
"Transitioned volumes cannot be converted to FlexGroup volumes." is not accurate

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap-7mode-transition#16]
Page: [Restrictions for transition](https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/concept_restrictions_for_transition.html)

The following restriction is not correct and should likely just be removed:

"Transitioned volumes cannot be converted to FlexGroup volumes."

The following documentation is accurate, and states that a transitioned volume can be converted into a FlexGroup volume but requires diagnostic level privilege:

https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-volume-task.html

**Comment by netapp-barbe** [comment]
Fixed: https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/concept_restrictions_for_transition.html
