### ISSUE TITLE
The example given in the doc is incorrect. 

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap-7mode-transition#17]
Page: [Preparing the cluster for transition](https://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/task_preparing_cluster_for_transition.html)

The following example shows the intercluster lif is created on a node vserver but it should be cluster vserver.  If you try following the below example, it will fail:

cluster1::> network interface create **-vserver cluster1-01** -lif intercluster_lif -role intercluster -home-node cluster1-01 -home-port e0c -address 192.0.2.130 -netmask 255.255.255.0

It should be 

cluster1::> network interface create -vserver cluster1 -lif intercluster_lif -role intercluster -home-node cluster1-01 -home-port e0c -address 192.0.2.130 -netmask 255.255.255.0

**Comment by netapp-barbe** [comment]
Thank you for the feedback, I'll make this change and follow up with any questions on this issue.

**Comment by netapp-barbe** [comment]
Fixed, thank you for the feedback: https://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/task_preparing_cluster_for_transition.html
