### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by wlori** [NetAppDocs/ontap-7mode-transition#27]
Page: [Guidelines for transitioning SnapLock volumes](https://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/concept_guidelines_for_transitioning_snaplock_volumes.html)

This verbiage is very confusing 
“You can transition 7-Mode SnapLock Compliance volumes only to SnapLock Compliance volumes in ONTAP 9.5 or earlier.” 

This can be read as SnapLock is only supported to version 9.5 and nothing newer. This is not the case and is directly contradicted in the same guide. 

Please update this page to match with the actual supported version. 

“The 7-Mode Transition Tool supports the transition of SnapLock volumes to target clusters running any ONTAP 9.0 release except 9.6.” - https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/concept_support_for_transitioning_snaplock_volumes.html

**Comment by wlori** [comment]
We also need this updated to show the issue with SnapLock and 9.10.1+. There are extra steps needed due to aggregates that can now have SnapLock and non-snaplock volumes. These steps should be well documented.

**Comment by netapp-pcarriga** [comment]
@wlori - Thank you for your feedback. We will review and update the documentation accordingly.
