### ISSUE TITLE
Breadcrumbs in 7MTT docs contain incorrect spelling

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-7mode-transition#5]
See the attached screenshot

![image](https://user-images.githubusercontent.com/36739591/118492419-fb9ff280-b6ed-11eb-9fca-abaa7dc86e8f.png)

This should say "7-Mode". Note the hyphen and capitalization of the M.

**Comment by adamn-ntap** [comment]
@netapp-aherbin and @netapp-ehoffman  - is this something @dmajones has to fix?

**Comment by dmajones** [comment]
@adamn-ntap Yes, it is. I have updated the breadcrumb to reflect **"7-Mode"** in the product name. 
![image](https://user-images.githubusercontent.com/53550488/118562322-b6011b00-b729-11eb-8719-a3bb085c8f51.png)
