### ISSUE TITLE
please add links to the specific version docs

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-7mode-transition#6]
Page: [ONTAP target releases supported by the 7-Mode Transition Tool](https://docs.netapp.com/us-en/ontap-7mode-transition/install-admin/concept_ontap_target_releases_supported_by_7mtt.html)

i couldnt find where in github i can access the specific docs. 

would be nice to hyper link the version to the product doc

thanks

**Comment by loganbaez** [comment]
here is a link to all the docs:
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61584&archive=true

**Comment by netapp-barbe** [comment]
Thanks Logan, this will be fixed in the 3.4.0 release
