### ISSUE TITLE
Link to 7mtt release notes is broken

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap-7mode-transition#9]
Page: [Transition overview](https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/concept_transition_overview.html)

Be sure to consult the current 7-Mode Transition Tool Release Notes for the latest information about supported target releases and known issues.

7-Mode Transition Tool Release Notes

https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/releasenotes.html

the old doc site states release notes are still on NSS:

https://docs.netapp.com/ontap-9/topic/com.netapp.ndc.ontap-new-home/GUID-E50669E2-2CC4-49D6-9468-3482F5DD34AA.html

7-Mode Transition Tool Release Notes remain available as PDF through the NetApp Support Site (login required).

**Comment by netapp-forry** [comment]
Thanks Logan -- will fix ASAP.

**Comment by netapp-barbe** [comment]
Hi Logan, sorry, I know this was fixed a while ago, but I must have forgotten to close the issue. I really appreciate your feedback!
